"""
This file collects and stores the web elements
used throughout the code base
"""

outdoor = ".Navigation__StyledNav-foe42i-1.dTvwCR > ul > li:nth-of-type(10)"
cookies = "button#onetrust-accept-btn-handler"
item = ".ProductGrid__StyledGrid-zyj4tq-0.kzNPPS > div:nth-of-type(2)"
body = "[data-testid=popup-backdrop]"
add_btn = ".blockAddActions__btn.blockAddActions__btn_show.btn-primary.js-addToCartBtn.jsProductInfo__btn.qa-addToCartBtn"
show_cart = ".HybridLink__StyledAnchor-sc-17cu3nf-0.IconsButtonTray__IconLink-sc-1yhxsuu-8.eIDzJT.gKUcLA.qa-header-cart-link svg"
cart_icon = ".CountBubble__StyledBadgeCount-zcrv3m-0.fcreeV.qa-header-cart-counter"
value_1 = "1"
value_2 = "2"
value_3 = "3"
cart_item = ".blockCartProduct__info"
chair = "Garten-Lounge-Set Bo, 4-tlg."
candle = "Duftkerze Bliss (Kokosnuss)"
crate = "Klappbox Coconut Milk, stapelbar, klein"
cart = "form#cart-items-list-form"
cookie_box = "div#onetrust-banner-sdk  .ot-sdk-row"
decor = "ul > li:nth-of-type(5)"
home = ".HybridLink__StyledLink-sc-17cu3nf-1.OneHeader__BigLogo-sc-78bzez-4.eFpPvi.gJHDNv"
nursery = ".Navigation__StyledNav-foe42i-1.dTvwCR > ul > li:nth-of-type(9)"
